spring.application.name=BankManagementApp
spring.datasource.url=jdbc:mysql://localhost:3306/bankdb
spring.datasource.name=root
spring.datasource.password=ovi11@sgos

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
